spring:
  application:
    name: field-service

  datasource:
    url: jdbc:postgresql://db-product-service:5432/product
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

server:
  port: 8081